default: &default
  adapter: 
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  timeout: 5000
  username: 
  password: 
  host: 
  port:

development:
  <<: *default
  database: docker_sinatra_development

